[meta]
name=Gruvbox Dark
description=Gruvbox — a retro groove color scheme with warm contrast
accent=#d79921

[gtk]
theme=gruvbox-material-gtk

[wm]
theme=Flatabulous-openbox
themerc=gruvbox

[qt]
style=Fusion
palette=gruvbox-dark

[icons]
theme=Tela-circle-dark

[cursor]
theme=bibata-modern
size=24

[fonts]
ui=Noto Sans,10
mono=JetBrains Mono Nerd Font,10
wm=Noto Sans,10

[panel]
opacity=85
background=rgba(40,40,40,217)

[colors]
active_bg=#504945
active_fg=#ebdbb2
inactive_bg=#282828
inactive_fg=#928374
border_active=#d79921
border_inactive=#504945
menu_bg=#282828
menu_fg=#ebdbb2
menu_active_bg=#d79921
menu_active_fg=#282828
button_close=#cc241d
button_maximize=#98971a
button_iconify=#d79921
