#!/bin/bash
# Wallust Setup — Dynamic Color Scheme Generation
# Installs wallust (Rust pywal) and configures templates
# for auto-generating colors from wallpapers.
#
# Usage:
#   bash wallust-setup.sh              # Install + configure
#   bash wallust-setup.sh --dry-run    # Preview only
#   bash wallust-setup.sh --apply      # Apply to current wallpaper

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/scripts/utils/lib.sh"

DRY_RUN=false
FORCE=false
APPLY=false

for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --force|-f) FORCE=true ;;
        --apply) APPLY=true ;;
        --help|-h)
            printf "Wallust Setup — Dynamic Color Scheme Generator\n\n"
            printf "Usage: bash wallust-setup.sh [options]\n\n"
            printf "Options:\n"
            printf "  --apply        Apply colors to current wallpaper\n"
            printf "  --dry-run      Preview only\n"
            printf "  --help, -h     Show this help\n"
            exit 0
            ;;
    esac
done

print_header "Wallust Setup"

# --- Install wallust ---
install_wallust() {
    if cmd_exists wallust; then
        log_ok "wallust already installed: $(wallust --version 2>/dev/null || echo 'ok')"
        return 0
    fi

    log_step "Installing wallust"

    # Try cargo first
    if cmd_exists cargo; then
        log_dim "  building from source via cargo..."
        cargo install wallust 2>/dev/null && {
            log_ok "wallust installed via cargo"
            return 0
        }
    fi

    # Try pre-built binary
    log_dim "  downloading pre-built binary..."
    local arch
    arch="$(uname -m)"
    local url="https://github.com/explosion-mental/wallust/releases/latest/download/wallust-${arch}-unknown-linux-musl"
    local dest="/usr/local/bin/wallust"

    if download "$url" "$dest" "wallust binary"; then
        chmod +x "$dest"
        log_ok "wallust installed from pre-built binary"
        return 0
    fi

    log_error "Could not install wallust"
    log_info "Install manually: cargo install wallust"
    log_info "Or: https://github.com/explosion-mental/wallust"
    return 1
}

install_wallust

# --- Create wallust config directory ---
WALLUST_DIR="$HOME/.config/wallust"
mkdir -p "$WALLUST_DIR"

# --- Generate default config if missing ---
if [ ! -f "$WALLUST_DIR/wallust.toml" ]; then
    log_step "Generating wallust config"
    if cmd_exists wallust; then
        wallust init 2>/dev/null || true
        if [ -f "$WALLUST_DIR/wallust.toml" ]; then
            log_ok "Generated wallust.toml"
        fi
    fi
fi

# --- Create templates for our configs ---
log_step "Creating wallust templates"

# Labwc themerc template
cat > "$WALLUST_DIR/themerc-override" << 'TEMPLATE'
# Auto-generated by wallust — do not edit manually
# Regenerate: wallust <wallpaper>

active_bg=COLOR1
active_fg=COLOR7
inactive_bg=COLOR0
inactive_fg=COLOR8
menu_bg=COLOR0
menu_fg=COLOR7
menu_active=COLOR4
menu_active_fg=COLOR0
maximized_bg=COLOR1
maximized_fg=COLOR7
minimized_bg=COLOR1
minimized_fg=COLOR7
placed_bg=COLOR1
placed_fg=COLOR7
shaded_bg=COLOR1
shaded_fg=COLOR7
unfocused_bg=COLOR0
unfocused_fg=COLOR8
TEMPLATE
log_ok "Created themerc-override template"

# Dunst notification template
cat > "$WALLUST_DIR/dunstrc" << 'TEMPLATE'
# Auto-generated by wallust — do not edit manually

[global]
    frame_color = COLOR0
    highlight = COLOR4

[urgency_low]
    background = COLOR0
    foreground = COLOR7

[urgency_normal]
    background = COLOR0
    foreground = COLOR7

[urgency_critical]
    background = COLOR1
    foreground = COLOR7
    highlight = COLOR1
TEMPLATE
log_ok "Created dunstrc template"

# GTK3 settings template
cat > "$WALLUST_DIR/gtk-3.0-settings.ini" << 'TEMPLATE'
# Auto-generated by wallust — do not edit manually

[Settings]
gtk-theme-name=Nordic
gtk-icon-theme-name=Tela
gtk-cursor-theme-name=breeze_cursors
gtk-cursor-theme-size=24
gtk-font-name=Noto Sans 10
gtk-application-prefer-dark-theme=true
gtk-decoration-button-layout=menu:minimize,maximize,close
TEMPLATE
log_ok "Created gtk-3.0-settings.ini template"

# Rofi theme template
cat > "$WALLUST_DIR/rofi-theme.rasi" << 'TEMPLATE'
/* Auto-generated by wallust — do not edit manually */

* {
    bg:         COLOR0F2;
    bg-alt:     COLOR1F2;
    fg:         COLOR7;
    fg-alt:     COLOR8;
    accent:     COLOR4;
    urgent:     COLOR1;
    selected:   COLOR4F2;
}
TEMPLATE
log_ok "Created rofi-theme.rasi template"

# --- Create apply script ---
cat > "$HOME/.local/bin/wallust-apply" << 'APPLYSCRIPT'
#!/bin/bash
# Apply wallust colors to all configs
# Usage: wallust-apply <wallpaper>

WALLPAPER="$1"
if [ -z "$WALLPAPER" ] || [ ! -f "$WALLPAPER" ]; then
    echo "Usage: wallust-apply <wallpaper-path>"
    exit 1
fi

WALLUST_DIR="$HOME/.config/wallust"

# Generate colors
wallust "$WALLPAPER" 2>/dev/null

# Apply labwc themerc
if [ -f "$WALLUST_DIR/themerc-override" ]; then
    cp "$WALLUST_DIR/themerc-override" "$HOME/.config/labwc/themerc-override"
    echo "Applied labwc themerc"
fi

# Apply dunst config
if [ -f "$WALLUST_DIR/dunstrc" ]; then
    cp "$WALLUST_DIR/dunstrc" "$HOME/.config/dunst/dunstrc"
    echo "Applied dunst config"
    pkill -USR1 dunst 2>/dev/null || true
fi

# Apply rofi theme
if [ -f "$WALLUST_DIR/rofi-theme.rasi" ]; then
    mkdir -p "$HOME/.config/rofi"
    cp "$WALLUST_DIR/rofi-theme.rasi" "$HOME/.config/rofi/theme.rasi"
    echo "Applied rofi theme"
fi

# Reconfigure labwc
labwc -r 2>/dev/null

echo "Wallust colors applied from: $WALLPAPER"
APPLYSCRIPT
chmod +x "$HOME/.local/bin/wallust-apply" 2>/dev/null || true
log_ok "Created wallust-apply script at ~/.local/bin/"

# --- Apply if requested ---
if [ "$APPLY" = true ]; then
    WALLPAPER=""
    if [ -f "$HOME/.config/labwc/wallpaper" ]; then
        WALLPAPER=$(cat "$HOME/.config/labwc/wallpaper")
    fi
    if [ -n "$WALLPAPER" ] && [ -f "$WALLPAPER" ]; then
        log_step "Applying wallust to current wallpaper"
        bash "$HOME/.local/bin/wallust-apply" "$WALLPAPER"
    else
        log_warn "No wallpaper found to apply"
    fi
fi

print_summary "Wallust Setup" "ok" "Dynamic theming ready. Use: wallust-apply <wallpaper>"
