[General]
version=2.1.0

[Qt]
style=Fusion
colorScheme=default
font=Noto Sans,10,-1,5,50,0,0,0,0,0
fixedFont=Noto Sans Mono,10,-1,5,50,0,0,0,0,0
iconTheme=breeze-dark
doubleClickInterval=400
cursorFlashTime=1000
wheelScrollLines=3
