[General]
__userfile__=~/.config/lxqt/lxqt-powermanagement.conf
icon_theme=breeze-dark

[Battery]
low_battery_level=15
critical_battery_level=5
action_on_critical_battery=Hibernate

[Idle]
idleness_timeout=300
action_on_idleness=TurnOffScreen
lock_on_suspend=true

[Lid]
action_on_lid_close_ac=Suspend
action_on_lid_close_battery=Suspend

[PowerButton]
action=Ask

[SuspendButton]
action=Suspend

[HibernateButton]
action=Hibernate
