[General]
__userfile__=~/.config/lxqt/lxqt-notificationd.conf
width=300
spacing=5
server_enabled=true
blacklisted_apps=

[Server]
placement=top-right
margin_x=10
margin_y=30
width=320
timeout=5000
max_lines=5

[Styling]
background_color=rgba(30, 30, 30, 230)
text_color=#eceff4
border_color=#81a1c1
border_width=1
border_radius=4
