#!/bin/bash
# LXQt Rice - System Fetch Tool Installer
# =========================================
# Installs and configures system info fetch tools (neofetch/fastfetch/hyfetch)
# for display in terminal on session start.
#
# Usage:
#   bash neofetch.sh                    # Interactive
#   bash neofetch.sh fastfetch          # Install specific tool
#   bash neofetch.sh --list             # List available tools
#   bash neofetch.sh --all              # Install everything
#   bash neofetch.sh --config only      # Only write config files (no install)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/scripts/utils/lib.sh"

# Tools to install via package manager
PACKAGE_TOOLS=(
  "neofetch|neofetch|Classic system info tool (Python)"
  "fastfetch|fastfetch|Modern system info tool (C, much faster)"
  "hyfetch|hyfetch|Neofetch with LGBTQ+ pride flags"
  "pfetch|pfetch|Minimal system info tool (shell)"
  "screenfetch|screenfetch|Multi-platform fetch tool"
)

# Configurations to write
write_neofetch_config() {
  local config_dir="$HOME/.config/neofetch"
  local config_file="$config_dir/config.conf"

  log_step "Writing neofetch configuration"

  if [ "$DRY_RUN" = "true" ]; then
    log_dim "  [DRY-RUN] Would write: $config_file"
    return 0
  fi

  mkdir -p "$config_dir"

  cat > "$config_file" << 'NEOFIX'
# neofetch config — generated by LXQt Rice scripts
# See: https://github.com/dylanaraps/neofetch/wiki

print_info() {
    info title
    info underline
    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "Terminal Font" term_font
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
    info cols
}

# Image settings
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=(4 6 7 8)
bold="on"
gap=3

# Color block
color_blocks="on"
block_width=3
block_height=1
col_offset="auto"
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_style="elapsed+total"

# Kernel
kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
uptime_shorthand="tiny"

# CPU
cpu_display="info"
cpu_speed="on"
cpu_cores="on"
cpu_temp="on"

# GPU
gpu_brand="on"
gpu_type="all"

# Memory
memory_unit="mib"

# Packages
package_managers="on"
shell_path="off"

# Theme
gtk2="on"
gtk3="on"
de="on"
wm="on"
wm_theme="on"
term="on"
term_font="on"
NEOFIX

  log_ok "neofetch config written"
}

write_fastfetch_config() {
  local config_dir="$HOME/.config/fastfetch"
  local config_file="$config_dir/config.jsonc"

  log_step "Writing fastfetch configuration"

  if [ "$DRY_RUN" = "true" ]; then
    log_dim "  [DRY-RUN] Would write: $config_file"
    return 0
  fi

  mkdir -p "$config_dir"

  cat > "$config_file" << 'FASTFIX'
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "auto",
    "padding": {
      "top": 1,
      "left": 2
    }
  },
  "display": {
    "separator": " → ",
    "colorKeys": "cyan",
    "colorTitle": "blue"
  },
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "display",
    "de",
    "wm",
    "wmtheme",
    "theme",
    "icons",
    "font",
    "cursor",
    "terminal",
    "terminalfont",
    "cpu",
    "gpu",
    "memory",
    "disk",
    "battery",
    "localip",
    "bluetooth",
    "colors",
    "separator",
    "break"
  ]
}
FASTFIX

  log_ok "fastfetch config written"
}

write_hyfetch_config() {
  local config_file="$HOME/.config/hyfetch.json"

  log_step "Writing hyfetch configuration"

  if [ "$DRY_RUN" = "true" ]; then
    log_dim "  [DRY-RUN] Would write: $config_file"
    return 0
  fi

  cat > "$config_file" << 'HYFIX'
{
  "preset": "transgender",
  "mode": "light",
  "light_dark_mode": true,
  "fetch": "neofetch"
}
HYFIX

  log_ok "hyfetch config written"
}

# Add neofetch to labwc autostart if not already present
add_to_autostart() {
  local tool="$1"
  local autostart="$HOME/.config/labwc/autostart"

  if [ ! -f "$autostart" ]; then
    log_warn "labwc autostart not found: $autostart"
    log_dim "  Skipping autostart entry (install dotfiles first)"
    return 0
  fi

  local entry="# System fetch on terminal open — managed by lxqt-rice"
  if grep -q "neofetch\|fastfetch\|pfetch\|screenfetch" "$autostart"; then
    log_dim "  fetch tool already in autostart"
    return 0
  fi

  if [ "$DRY_RUN" = "true" ]; then
    log_dim "  [DRY-RUN] Would add to autostart: $tool"
    return 0
  fi

  # We don't auto-add — users can run fetch manually in their shell rc
  log_dim "  tip: add '$tool' to ~/.bashrc or ~/.zshrc to show on terminal start"
}

list_tools() {
  print_header "Available System Fetch Tools"
  printf "\n"
  printf "%-20s %s\n" "TOOL" "DESCRIPTION"
  printf "%s\n" "──────────────────────────────────────────"
  for entry in "${PACKAGE_TOOLS[@]}"; do
    IFS='|' read -r name _ desc <<< "$entry"
    printf "  ${GREEN}%-18s${RST} %s\n" "$name" "$desc"
  done
  printf "\n"
}

install_package() {
  local name="$1" desc="$2"

  log_step "Installing: $name"

  if cmd_exists "$name"; then
    log_ok "already installed: $name ($(command -v "$name"))"
    return 0
  fi

  if [ "$DRY_RUN" = "true" ]; then
    log_dim "  [DRY-RUN] Would install: $name"
    return 0
  fi

  log_dim "  installing via package manager..."
  if pkg_install "$name"; then
    log_ok "installed: $name"
    return 0
  fi

  # Try pip for neofetch/hyfetch
  if [ "$name" = "neofetch" ] || [ "$name" = "hyfetch" ]; then
    if cmd_exists "pip3"; then
      pip3 install --user "$name" 2>/dev/null && log_ok "installed via pip: $name" && return 0
    fi
  fi

  # Manual install for fastfetch if package manager fails
  if [ "$name" = "fastfetch" ]; then
    log_dim "  trying manual download..."
    local url
    local arch
    arch="$(uname -m)"
    case "$arch" in
      x86_64) url="https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.tar.gz" ;;
      aarch64) url="https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-aarch64.tar.gz" ;;
      *) log_warn "unsupported arch: $arch"; return 1 ;;
    esac

    local tmpdir="$CACHE_DIR/fastfetch"
    rm -rf "$tmpdir"
    mkdir -p "$tmpdir"
    download_extract "$url" "$tmpdir" 1 "fastfetch binary"
    find "$tmpdir" -name "fastfetch" -type f -exec cp {} "$HOME/.local/bin/" \; 2>/dev/null || true
    find "$tmpdir" -name "flashfetch" -type f -exec cp {} "$HOME/.local/bin/" \; 2>/dev/null || true
    rm -rf "$tmpdir"
    if [ -f "$HOME/.local/bin/fastfetch" ]; then
      chmod +x "$HOME/.local/bin/fastfetch"
      log_ok "manually installed: fastfetch -> ~/.local/bin/fastfetch"
      return 0
    fi
  fi

  log_warn "Could not install: $name"
  return 1
}

main() {
  print_header "LXQt Rice — System Fetch Tool Installer"

  require_cmds curl tar || true  # not fatal, some may already be installed

  local do_install=true
  local do_config=true
  local targets=()

  if [ $# -eq 0 ]; then
    list_tools
    printf "${BOLD}Enter tool names to install (space-separated) or 'all':${RST} "
    read -r input
    if [ "$input" = "all" ]; then
      for entry in "${PACKAGE_TOOLS[@]}"; do
        IFS='|' read -r name _ _ <<< "$entry"
        targets+=("$name")
      done
    elif [ "$input" = "none" ]; then
      do_install=false
      do_config=false
    else
      targets=($input)
    fi
  else
    for arg in "$@"; do
      case "$arg" in
        --list|-l) list_tools; return 0 ;;
        --all|-a)
          for entry in "${PACKAGE_TOOLS[@]}"; do
            IFS='|' read -r name _ _ <<< "$entry"
            targets+=("$name")
          done ;;
        --config) do_install=false; do_config=true ;;
        --no-config) do_config=false ;;
        --dry-run) DRY_RUN=true ;;
        --force|-f) FORCE=true ;;
        *) targets+=("$arg") ;;
      esac
    done
  fi

  local ok=true

  if [ "$do_install" = true ] && [ ${#targets[@]} -gt 0 ]; then
    for target in "${targets[@]}"; do
      local found=false
      for entry in "${PACKAGE_TOOLS[@]}"; do
        IFS='|' read -r name _ desc <<< "$entry"
        if [ "$name" = "$target" ]; then
          install_package "$name" "$desc" || ok=false
          found=true
          break
        fi
      done
      if [ "$found" = false ]; then
        log_error "Unknown tool: $target"
        ok=false
      fi
    done
  fi

  if [ "$do_config" = true ]; then
    if cmd_exists "neofetch"; then
      write_neofetch_config
    fi
    if cmd_exists "fastfetch" || [ -f "$HOME/.local/bin/fastfetch" ]; then
      write_fastfetch_config
    fi
    if cmd_exists "hyfetch"; then
      write_hyfetch_config
    fi
  fi

  if [ "$ok" = true ]; then
    print_summary "System fetch installer" "ok"
  else
    print_summary "System fetch installer" "fail"
    return 1
  fi
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  main "$@"
fi
