[General]
__userfile__=~/.config/lxqt/globalkeyshortcuts.conf

[Print.1]
Comment=Screenshot (Entire Screen)
Enabled=true
path=/usr/bin/grimshot
Arguments=save, screen

[Shift+Print.2]
Comment=Screenshot (Interactive/Area)
Enabled=true
path=/usr/bin/grimshot
Arguments=save, area

[Ctrl+Alt+T.3]
Comment=Terminal
Enabled=true
path=/usr/bin/qterminal

[Ctrl+Alt+E.4]
Comment=File Manager
Enabled=true
path=/usr/bin/pcmanfm-qt

[Alt+F2.5]
Comment=Show LXQt Runner
Enabled=true
path=/usr/bin/lxqt-runner

[XF86AudioMute.6]
Comment=Mute Audio
Enabled=true
path=/usr/bin/pactl
Arguments=set-sink-mute, @DEFAULT_SINK@, toggle

[XF86AudioRaiseVolume.7]
Comment=Raise Volume
Enabled=true
path=/usr/bin/pactl
Arguments=set-sink-volume, @DEFAULT_SINK@, +5%

[XF86AudioLowerVolume.8]
Comment=Lower Volume
Enabled=true
path=/usr/bin/pactl
Arguments=set-sink-volume, @DEFAULT_SINK@, -5%

[XF86MonBrightnessUp.9]
Comment=Brightness Up
Enabled=true
path=/usr/bin/brightnessctl
Arguments=s, +5%

[XF86MonBrightnessDown.10]
Comment=Brightness Down
Enabled=true
path=/usr/bin/brightnessctl
Arguments=s, 5%-

[Ctrl+Escape.11]
Comment=Task Manager
Enabled=true
path=/usr/bin/qps
