[General]
__userfile__=~/.config/lxqt/lxqt-runner.conf
width=400
list_width=400
show_on_top=true
clear_on_show=true
history_size=50

[dialog]
shortcut=Alt+F2
show_on_top=true
width=400
list_width=400
position=Center

[math]
enabled=true

[mimetypes]
enabled=true

[history]
enabled=true
history_size=50
