[Behavior]
BookmarkOpenMethod=0
CloseOnUnmount=true
ConfirmDelete=true
ConfirmTrash=true
CtrlRightClick=true
DesktopFolder=
DesktopFolderAsHome=false
DesktopFolderFollowsDir=false
DropMenu=true
ExecutableAsk=true
NoUsbTrash=true
PathInTitle=false
PerWindowSettings=false
SelectNewFiles=true
SingleWindow=true
SmoothScroll=true
SuCommand=lxqt-sudo %s
Terminal=qterminal -e %s
ThumbAlwaysLimit=2048
UseTrash=true

[Desktop]
Wallpaper=
WallpaperMode=stretch
BgColor=#000000
FgColor=#ffffff
TextBgColor=#000000
ShadowColor=#000000
Shadows=true
ShowHidden=false
SortColumn=0
SortOrder=0
IconSize=48
Tooltip=false
Visible=false

[FolderView]
Mode=icon
IconSize=48
BigIconSize=48
SidePaneIconSize=24
SortColumn=0
SortOrder=0
ShowHidden=false
DirFirst=true
CaseSensitiveSort=false
ShowTooltips=true
MaxThumbnailFileSize=4096
MaxThumbnailImageSize=1024

[System]
FallbackIconThemeName=hicolor
IconThemeName=breeze-dark
SuCommand=lxqt-sudo %s
Terminal=qterminal -e %s
